import Chance from "chance";

const chance = new Chance();
const email = chance.email();

describe('Registration', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3005')
    cy.get('#user-button')
      .click(15,20)
      .contains('Register')
      .click()
      .url()
      .should('eq','http://localhost:3005/signup')
  })

  it('Check errors', () => {
    cy.get('input[name="firstName"]')
      .type('A')
      .get('#submit-button')
      .click()
      .url()
      .should('eq','http://localhost:3005/signup')
      .get('input[name="firstName"]')
      .clear()
      .type('Arya')
      .should('have.value', 'Arya')
      .get('input[name="lastName"]')
      .type('Sharma')
      .should('have.value','Sharma')
      .get('input[name="email"]')
      .type(email)
      .should('have.value',email)
      .get('input[name="password"]')
      .type('123456')
      .should('have.value','123456')
      .get('#submit-button')
      .click()
      .url()
      .should('eq','http://localhost:3005/signup')
      .get('input[name="password2"]')
      .type('1234567')
      .should('have.value','1234567')
      .get('#submit-button')
      .click()
      .url()
      .should('eq','http://localhost:3005/signup')
  })
  
  it('Fill Correct Form and Submit', () => {
    cy.get('input[name="firstName"]')
      .type('Arya')
      .should('have.value', 'Arya')
      .get('input[name="lastName"]')
      .type('Sharma')
      .should('have.value','Sharma')
      .get('input[name="email"]')
      .type(email)
      .should('have.value',email)
      .get('input[name="password"]')
      .type('123456')
      .should('have.value','123456')
      .get('input[name="password2"]')
      .type('123456')
      .should('have.value','123456')
      .get('#submit-button')
      .click()
      .url()
      .should('eq','http://localhost:3005/')
  })
})

describe('Login', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3005')
    cy.get('#user-button')
      .click(15,20)
      .contains('Login')
      .click()
      .url()
      .should('eq','http://localhost:3005/login')
  })

  it('Check errors', () => {
    cy.get('input[name="email"]')
      .type(email)
      .should('have.value',email)
      .get('input[name="password"]')
      .type('1234567')
      .should('have.value','1234567')
      .get('#submit-button')
      .click()
      .url()
      .should('eq','http://localhost:3005/login')
  })
  
  it('Fill Correct Form and Submit', () => {
    cy.get('input[name="email"]')
    .type(email)
    .should('have.value',email)
    .get('input[name="password"]')
    .type('123456')
    .should('have.value','123456')
    .get('#submit-button')
    .click()
    .url()
    .should('eq','http://localhost:3005/')
  })
})



